### ISSUE TITLE
test suite is filing with Python 3.14

### ISSUE THREAD

**Issue by tijuca** [django-webtest/django-webtest#140]
Hello,

while trying to package the most recent version 1.9.14 within Debian unstable the test suite is failing with Python 3.14.

```
: pybuild base:317: cd django_webtest_tests && python3.14 runtests.py
Creating test database for alias 'default'...
Found 61 test(s).
System check identified no issues (0 silenced).
.EEEEEEEEEEE...EEE.E..EEEEEEE....E.E............s.E.EEE......
======================================================================
ERROR: test_custom_middleware (django_webtest_tests.testapp_tests.tests.AuthTest.test_custom_middleware)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-webtest-1.9.14/django_webtest_tests/testapp_tests/tests.py", line 240, in test_custom_middleware
    response = self.app.get('/template/index.html', user=self.user)
  File "/build/django-webtest-1.9.14/django_webtest/__init__.py", line 138, in get
    response = super(DjangoTestApp, self).get(url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/webtest/app.py", line 328, in get
    return self.do_request(req, status=status,
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
                           expect_errors=expect_errors)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/django-webtest-1.9.14/django_webtest/__init__.py", line 100, in do_request
    response = super(DjangoTestApp, self).do_request(req, status,
                                                     expect_errors)
  File "/usr/lib/python3/dist-packages/webtest/app.py", line 627, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/usr/lib/python3/dist-packages/webob/request.py", line 1309, in send
    status, headers, app_iter, exc_info = self.call_application(
                                          ~~~~~~~~~~~~~~~~~~~~~^
        application, catch_exc_info=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python3/dist-packages/webtest/lint.py", line 196, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python3/dist-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/build/django-webtest-1.9.14/django_webtest/middleware.py", line 64, in __call__
    return self.get_response(request)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/build/django-webtest-1.9.14/django_webtest_tests/urls.py", line 33, in simple_template_render
    return render(request, template_name, {
        'user': request.user,
    ...<2 lines>...
        'spam': None,
    })
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 111, in instrumented_test_render
    template_rendered.send(sender=self, template=self, context=context)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/test/client.py", line 267, in store_rendered_templates
    store["context"].append(copy(context))
                            ~~~~^^^^^^^^^
  File "/usr/lib/python3.14/copy.py", line 82, in copy
    return copier(x)
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 158, in __copy__
    duplicate = super().__copy__()
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 39, in __copy__
    duplicate.dicts = self.dicts[:]
    ^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes

...
======================================================================
ERROR: test_rendered_templates (django_webtest_tests.testapp_tests.tests.TemplateContextTest.test_rendered_templates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-webtest-1.9.14/django_webtest_tests/testapp_tests/tests.py", line 157, in test_rendered_templates
    response = self.app.get('/template/index.html')
  File "/build/django-webtest-1.9.14/django_webtest/__init__.py", line 138, in get
    response = super(DjangoTestApp, self).get(url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/webtest/app.py", line 328, in get
    return self.do_request(req, status=status,
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
                           expect_errors=expect_errors)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/django-webtest-1.9.14/django_webtest/__init__.py", line 100, in do_request
    response = super(DjangoTestApp, self).do_request(req, status,
                                                     expect_errors)
  File "/usr/lib/python3/dist-packages/webtest/app.py", line 627, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/usr/lib/python3/dist-packages/webob/request.py", line 1309, in send
    status, headers, app_iter, exc_info = self.call_application(
                                          ~~~~~~~~~~~~~~~~~~~~~^
        application, catch_exc_info=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python3/dist-packages/webtest/lint.py", line 196, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/usr/lib/python3/dist-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/build/django-webtest-1.9.14/django_webtest/middleware.py", line 44, in __call__
    return self.get_response(request)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
                           ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 141, in response_for_exception
    response = handle_uncaught_exception(
        request, get_resolver(get_urlconf()), sys.exc_info()
    )
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/build/django-webtest-1.9.14/django_webtest_tests/urls.py", line 33, in simple_template_render
    return render(request, template_name, {
        'user': request.user,
    ...<2 lines>...
        'spam': None,
    })
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/test/utils.py", line 111, in instrumented_test_render
    template_rendered.send(sender=self, template=self, context=context)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/test/client.py", line 267, in store_rendered_templates
    store["context"].append(copy(context))
                            ~~~~^^^^^^^^^
  File "/usr/lib/python3.14/copy.py", line 82, in copy
    return copier(x)
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 158, in __copy__
    duplicate = super().__copy__()
  File "/usr/lib/python3/dist-packages/django/template/context.py", line 39, in __copy__
    duplicate.dicts = self.dicts[:]
    ^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes

----------------------------------------------------------------------
Ran 61 tests in 4.006s

FAILED (errors=28, skipped=1)
Destroying test database for alias 'default'...
E: pybuild pybuild:389: test: plugin custom failed with: exit code=1: cd django_webtest_tests && python3.14 runtests.py
```
Running the test with Python 3.13 doesn't provoke any issues.

**Comment by gawel** [comment]
Hi,

Thanks for the report. Do you know if django itself works with 3.14 ? It looks like the exception come from django/template/context.py so I guess this issue may be auto-fixed later

**Comment by tijuca** [comment]
Mhh, that might be true.
So far I know Django 6 isn't fully ready or adjusted for Python 3.14.
